python main.py --do_train=True --seed=10 --batch_size=128
python main.py --do_train=True --seed=20 --batch_size=128
python main.py --do_train=True --seed=30 --batch_size=128
python main.py --do_train=True --seed=42 --batch_size=128
python main.py --do_train=True --seed=50 --batch_size=128
python main.py --do_train=True --seed=60 --batch_size=128
python main.py --do_train=True --seed=70 --batch_size=128
python main.py --do_train=True --seed=80 --batch_size=128
python main.py --do_train=True --seed=90 --batch_size=128
python main.py --do_train=True --seed=100 --batch_size=128
python main.py --do_train=True --seed=110 --batch_size=128
python main.py --do_train=True --seed=120 --batch_size=128
python main.py --do_train=True --seed=130 --batch_size=128
python main.py --do_train=True --seed=140 --batch_size=128
python main.py --do_train=True --seed=150 --batch_size=128
python main.py --do_train=True --seed=160 --batch_size=128
python main.py --do_train=True --seed=170 --batch_size=128
python main.py --do_train=True --seed=180 --batch_size=128
python main.py --do_train=True --seed=190 --batch_size=128
python main.py --do_train=True --seed=200 --batch_size=128